# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application CI with Docker

on:
  push:
    branches: [ dev_main ]
  pull_request:
#     branches: [ dev_main ]
    types:
      - closed
    branches:
      - dev_main
      - longpb_dev

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: huylq1999/webappstudent # change to your DockerHub
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }} # set secret in git setting
        password: ${{ secrets.DOCKER_PASSWORD }}
