# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application CI with Docker

on: [push, pull_request]
#   push:
#     branches: [ dev_main, longpb_dev ]
#   pull_request:
#     branches: [ dev_main, longpb_dev ]
    

jobs:  

  build:

    runs-on: ubuntu-latest
    env:
        username: ${{ secrets.DOCKER_USERNAME }} # set secret in git setting
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
        - uses: actions/checkout@v2
        - name: Docker Login
            run:docker login -u $username -p $password
        - name: Build Docker
            run:docker build ./ -t huylq1999/webappstudent
        - name: Push Docker
            docker push
                
    
        
        
#       uses: mr-smithers-excellent/docker-build-push@v4
#       with:
#         image: huylq1999/webappstudent # change to your DockerHub
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }} # set secret in git setting
#         password: ${{ secrets.DOCKER_PASSWORD }}
